-- Insert Press Entries Data Script
-- This script seeds the press_entries table with initial data
-- Prerequisites: tables users(id), press_entries must exist

BEGIN;

-- Insert press entries from the hardcoded data
INSERT INTO press_entries (
    title, 
    release_date, 
    category_id, 
    source_url, 
    content_html, 
    status, 
    visibility, 
    cover_image_url, 
    cover_image_gcp_key, 
    publish_at, 
    created_by, 
    updated_by, 
    created_at, 
    updated_at
) VALUES 
(
    'Algoma University Marks Milestone with Earth Turning Gathering for Makwa Waakaa''igan',
    '2025-06-22',
    NULL,
    'https://algomau.ca/news/algoma-university-marks-milestone-with-earth-turning-gathering-for-makwa-waakaaigan/',
    '<p>Algoma University marks a significant milestone with the earth turning gathering for the new Centre for Reconciliation (Makwa Waakaa''igan).</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2025-06-22T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Algoma U earth turning marks a new chapter toward reconciliation',
    '2025-06-21',
    NULL,
    'https://www.sootoday.com/local-news/algoma-u-earth-turning-marks-a-new-chapter-toward-reconciliation-10839977',
    '<p>The earth turning ceremony at Algoma University marks a new chapter in the university''s commitment to reconciliation with Indigenous communities.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2025-06-21T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Building a Path to Understanding: Construction Begins on New Centre for Reconciliation',
    '2025-06-20',
    NULL,
    'https://www.ctvnews.ca/northern-ontario/video/2025/06/20/construction-begins-on-important-centre-in-the-sault/',
    '<p>Construction has officially begun on the new Centre for Reconciliation at Algoma University, a significant step in the university''s reconciliation efforts.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2025-06-20T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Makwa Waakaa''igan Earth Turning Gathering - watch on CSAA youtube channel',
    '2025-06-20',
    NULL,
    'https://www.youtube.com/live/F8ZFB3yJ8GM',
    '<p>Watch the Makwa Waakaa''igan Earth Turning Gathering live on the CSAA YouTube channel.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2025-06-20T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Shirley Horn - Algoma University honours academic excellence and resilience',
    '2025-06-14',
    NULL,
    'https://www.sootoday.com/local-news/algoma-university-honours-academic-excellence-and-resilience-10812166',
    '<p>Algoma University honours Shirley Horn for her contributions to academic excellence and resilience in the community.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2025-06-14T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Front lawn assessed before AU builds',
    '2024-11-05',
    NULL,
    'https://www.saultstar.com/news/local-news/front-lawn-assessed-before-au-builds',
    '<p>Algoma University front lawn undergoes assessment before construction of the new Centre for Reconciliation.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2024-11-05T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'DR. PETER CHOW: To dig or not to dig - thorough investigation needed into claims of genocide at residential schools',
    '2024-11-04',
    NULL,
    'https://www.saultstar.com/opinion/dr-peter-chow-to-dig-or-not-to-dig-thorough-investigation-needed-into-claims-of-genocide-at-residential-schools',
    '<p>Dr. Peter Chow discusses the need for thorough investigation into historical claims related to residential schools.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2024-11-04T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Algoma University Launches Makwa Waakaa''igan: Centre for Reconciliation',
    '2024-10-15',
    NULL,
    'https://algomau.ca/news/makwa-waakaaigan/',
    '<p>Algoma University officially launches Makwa Waakaa''igan, the Centre for Reconciliation, a dedicated space for dialogue and understanding.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2024-10-15T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Indigenous Leadership Program Expands at Algoma University',
    '2024-09-20',
    NULL,
    'https://algomau.ca/news/indigenous-leadership-program/',
    '<p>Algoma University expands its Indigenous Leadership Program to provide more opportunities for Indigenous students.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2024-09-20T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
),
(
    'Community Engagement Initiative Strengthens University-Local Partnerships',
    '2024-08-30',
    NULL,
    'https://algomau.ca/news/community-engagement/',
    '<p>Algoma University announces new community engagement initiatives to strengthen partnerships with local organizations.</p>',
    'published',
    'public',
    NULL,
    NULL,
    '2024-08-30T10:00:00Z',
    NULL,
    NULL,
    NOW(),
    NOW()
);

COMMIT;
